In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("qoute_dataset.csv")
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [3]:
quotes=df['quote']
quotes=quotes.str.lower()
quotes

0       “the world as we have created it is a process ...
1       “it is our choices, harry, that show what we t...
2       “there are only two ways to live your life. on...
3       “the person, be it gentleman or lady, who has ...
4       “imperfection is beauty, madness is genius and...
                              ...
3033        the past beats inside me like a second heart.
3034    damn, claire. warn a guy before you do a face-...
3035    can you be a girl for a few seconds?""i'm alwa...
3036    that's what fiction is for. it's for getting a...
3037    if we have no peace, it is because we have for...
Name: quote, Length: 3038, dtype: object

In [4]:
import re
quotes = quotes.apply(lambda x: re.sub(r'[^\w\s]', '', x))
display(quotes.head())

0    the world as we have created it is a process o...
1    it is our choices harry that show what we trul...
2    there are only two ways to live your life one ...
3    the person be it gentleman or lady who has not...
4    imperfection is beauty madness is genius and i...
Name: quote, dtype: object

In [5]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [6]:
vocab_size=8723
token=Tokenizer(
    num_words=vocab_size,
)
token.fit_on_texts(quotes)

In [7]:

word_index = token.word_index
print(len(word_index))
list(word_index.items())[:10]

8723

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [8]:
sequence=token.texts_to_sequences(quotes)

In [9]:
X=[]
y=[]
for seq in sequence:
    for i in range(1,len(seq)):
        X.append(seq[:i])
        y.append(seq[i])

len(X)

85211

In [10]:
maxlen=max(len(i) for i in X)
maxlen

745

In [11]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [12]:
X_padded=pad_sequences(X,maxlen=maxlen,padding='pre')
X_padded.shape

(85211, 745)

In [13]:
y=np.array(y)

In [14]:
from tensorflow.keras.utils import to_categorical
y_oneHot=to_categorical(y,num_classes=vocab_size)

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,SimpleRNN

In [16]:
embedding_dim=50
rnn_units=128

In [17]:
model=Sequential([
    Embedding(input_dim=vocab_size,output_dim=embedding_dim,input_length=maxlen),
])
model.add(
    SimpleRNN(units=rnn_units)
)
model.add(
    Dense(units=vocab_size,activation='softmax')
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [18]:
model.compile(
    optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy']
    )

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
lstm_model=Sequential([
    Embedding(input_dim=vocab_size,output_dim=embedding_dim,input_length=maxlen),
])
lstm_model.add(
    LSTM(units=rnn_units)
)
lstm_model.add(Dense(units=vocab_size,activation='softmax'))
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
epochs=100
batch_size=128

In [22]:
lstm_model.compile(
    optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy']
)
history = lstm_model.fit(
    X_padded, y_oneHot, epochs=epochs, batch_size=batch_size, verbose=1,validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 56ms/step - accuracy: 0.0389 - loss: 6.7089 - val_accuracy: 0.0456 - val_loss: 6.6364
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.0580 - loss: 6.2923 - val_accuracy: 0.0651 - val_loss: 6.5223
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 43s 57ms/step - accuracy: 0.0805 - loss: 6.0285 - val_accuracy: 0.0886 - val_loss: 6.4193
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 56ms/step - accuracy: 0.0999 - loss: 5.8037 - val_accuracy: 0.0973 - val_loss: 6.3842
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1120 - loss: 5.6150 - val_accuracy: 0.1057 - val_loss: 6.3571
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1209 - loss: 5.4464 - val_accuracy: 0.1078 - val_loss: 6.3745
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.1293 - loss: 5.2891 - val_accuracy: 0.1114 - val_loss: 6.3936
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1362 - loss: 5.1437 - val_accuracy: 0.1104 - val_loss: 6.4222
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1441 - loss: 5.0065 - val_accuracy: 0.1124 - val_loss: 6.4618
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.1509 - loss: 4.8754 - val_accuracy: 0.1135 - val_loss: 6.5054
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.1565 - loss: 4.7475 - val_accuracy: 0.1136 - val_loss: 6.5607
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1643 - loss: 4.6222 - val_accuracy: 0.1119 - val_loss: 6.6144
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.1725 - loss: 4.4985 - val_accuracy: 0.1114 - val_loss: 6.6730
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.1824 - loss: 4.3795 - val_accuracy: 0.1129 - val_loss: 6.7304
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.1937 - loss: 4.2597 - val_accuracy: 0.1111 - val_loss: 6.8054
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.2057 - loss: 4.1456 - val_accuracy: 0.1148 - val_loss: 6.8885
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2191 - loss: 4.0348 - val_accuracy: 0.1137 - val_loss: 6.9515
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.2356 - loss: 3.9286 - val_accuracy: 0.1132 - val_loss: 7.0145
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2503 - loss: 3.8291 - val_accuracy: 0.1143 - val_loss: 7.0875
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.2637 - loss: 3.7348 - val_accuracy: 0.1119 - val_loss: 7.1809
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.2770 - loss: 3.6455 - val_accuracy: 0.1131 - val_loss: 7.2710
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2892 - loss: 3.5634 - val_accuracy: 0.1125 - val_loss: 7.3320
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.3019 - loss: 3.4853 - val_accuracy: 0.1128 - val_loss: 7.4167
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3124 - loss: 3.4109 - val_accuracy: 0.1082 - val_loss: 7.4918
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.3236 - loss: 3.3406 - val_accuracy: 0.1110 - val_loss: 7.5546
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.3357 - loss: 3.2724 - val_accuracy: 0.1068 - val_loss: 7.6333
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3446 - loss: 3.2083 - val_accuracy: 0.1084 - val_loss: 7.7084
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 56ms/step - accuracy: 0.3553 - loss: 3.1461 - val_accuracy: 0.1087 - val_loss: 7.7782
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3651 - loss: 3.0868 - val_accuracy: 0.1057 - val_loss: 7.8513
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3759 - loss: 3.0285 - val_accuracy: 0.1048 - val_loss: 7.9246
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3845 - loss: 2.9736 - val_accuracy: 0.1061 - val_loss: 7.9985
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.3940 - loss: 2.9197 - val_accuracy: 0.1026 - val_loss: 8.0699
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.4021 - loss: 2.8680 - val_accuracy: 0.1017 - val_loss: 8.1255
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.4121 - loss: 2.8162 - val_accuracy: 0.1003 - val_loss: 8.1759
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4200 - loss: 2.7683 - val_accuracy: 0.1017 - val_loss: 8.2537
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4290 - loss: 2.7199 - val_accuracy: 0.1010 - val_loss: 8.3207
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.4370 - loss: 2.6730 - val_accuracy: 0.0994 - val_loss: 8.3727
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4458 - loss: 2.6275 - val_accuracy: 0.0975 - val_loss: 8.4341
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.4533 - loss: 2.5849 - val_accuracy: 0.0976 - val_loss: 8.4910
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4608 - loss: 2.5428 - val_accuracy: 0.0979 - val_loss: 8.5523
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4684 - loss: 2.5005 - val_accuracy: 0.1001 - val_loss: 8.6123
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.4768 - loss: 2.4607 - val_accuracy: 0.0960 - val_loss: 8.6759
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4849 - loss: 2.4200 - val_accuracy: 0.0986 - val_loss: 8.7360
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.4911 - loss: 2.3826 - val_accuracy: 0.0947 - val_loss: 8.7960
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4991 - loss: 2.3434 - val_accuracy: 0.0949 - val_loss: 8.8615
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.5044 - loss: 2.3079 - val_accuracy: 0.0958 - val_loss: 8.9074
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5123 - loss: 2.2722 - val_accuracy: 0.0943 - val_loss: 8.9579
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.5192 - loss: 2.2369 - val_accuracy: 0.0943 - val_loss: 9.0256
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.5262 - loss: 2.2033 - val_accuracy: 0.0973 - val_loss: 9.0910
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5321 - loss: 2.1710 - val_accuracy: 0.0931 - val_loss: 9.1428
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.5393 - loss: 2.1378 - val_accuracy: 0.0915 - val_loss: 9.1953
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.5443 - loss: 2.1062 - val_accuracy: 0.0923 - val_loss: 9.2777
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5507 - loss: 2.0759 - val_accuracy: 0.0929 - val_loss: 9.3218
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.5586 - loss: 2.0429 - val_accuracy: 0.0918 - val_loss: 9.3855
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 56ms/step - accuracy: 0.5636 - loss: 2.0146 - val_accuracy: 0.0915 - val_loss: 9.4219
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.5689 - loss: 1.9873 - val_accuracy: 0.0895 - val_loss: 9.4769
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5742 - loss: 1.9587 - val_accuracy: 0.0911 - val_loss: 9.5360
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.5811 - loss: 1.9320 - val_accuracy: 0.0895 - val_loss: 9.5779
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5866 - loss: 1.9045 - val_accuracy: 0.0878 - val_loss: 9.6554
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.5913 - loss: 1.8771 - val_accuracy: 0.0902 - val_loss: 9.6917
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.5962 - loss: 1.8534 - val_accuracy: 0.0875 - val_loss: 9.7476
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.6005 - loss: 1.8280 - val_accuracy: 0.0882 - val_loss: 9.8012
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6063 - loss: 1.8024 - val_accuracy: 0.0891 - val_loss: 9.8573
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.6105 - loss: 1.7804 - val_accuracy: 0.0860 - val_loss: 9.9131
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.6152 - loss: 1.7557 - val_accuracy: 0.0880 - val_loss: 9.9720
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6208 - loss: 1.7346 - val_accuracy: 0.0889 - val_loss: 10.0282
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6247 - loss: 1.7115 - val_accuracy: 0.0864 - val_loss: 10.0860
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6303 - loss: 1.6896 - val_accuracy: 0.0853 - val_loss: 10.1302
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6355 - loss: 1.6681 - val_accuracy: 0.0888 - val_loss: 10.1833
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.6383 - loss: 1.6469 - val_accuracy: 0.0841 - val_loss: 10.2362
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6427 - loss: 1.6255 - val_accuracy: 0.0843 - val_loss: 10.2959
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6474 - loss: 1.6052 - val_accuracy: 0.0835 - val_loss: 10.3518
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6511 - loss: 1.5875 - val_accuracy: 0.0851 - val_loss: 10.3905
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6544 - loss: 1.5670 - val_accuracy: 0.0813 - val_loss: 10.4576
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6593 - loss: 1.5476 - val_accuracy: 0.0831 - val_loss: 10.4920
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6625 - loss: 1.5308 - val_accuracy: 0.0841 - val_loss: 10.5495
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6658 - loss: 1.5126 - val_accuracy: 0.0833 - val_loss: 10.5994
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6712 - loss: 1.4918 - val_accuracy: 0.0841 - val_loss: 10.6565
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6759 - loss: 1.4739 - val_accuracy: 0.0791 - val_loss: 10.7209
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 56ms/step - accuracy: 0.6782 - loss: 1.4584 - val_accuracy: 0.0824 - val_loss: 10.7617
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.6814 - loss: 1.4422 - val_accuracy: 0.0814 - val_loss: 10.8091
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6858 - loss: 1.4246 - val_accuracy: 0.0831 - val_loss: 10.8631
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6898 - loss: 1.4071 - val_accuracy: 0.0814 - val_loss: 10.9068
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6929 - loss: 1.3927 - val_accuracy: 0.0834 - val_loss: 10.9481
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6958 - loss: 1.3774 - val_accuracy: 0.0793 - val_loss: 11.0073
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6998 - loss: 1.3622 - val_accuracy: 0.0797 - val_loss: 11.0600
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7039 - loss: 1.3468 - val_accuracy: 0.0808 - val_loss: 11.0969
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.7071 - loss: 1.3317 - val_accuracy: 0.0820 - val_loss: 11.1535
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7094 - loss: 1.3155 - val_accuracy: 0.0814 - val_loss: 11.2092
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7107 - loss: 1.3028 - val_accuracy: 0.0811 - val_loss: 11.2492
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7169 - loss: 1.2888 - val_accuracy: 0.0784 - val_loss: 11.3345
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7180 - loss: 1.2775 - val_accuracy: 0.0792 - val_loss: 11.3387
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7201 - loss: 1.2652 - val_accuracy: 0.0785 - val_loss: 11.3971
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7247 - loss: 1.2489 - val_accuracy: 0.0796 - val_loss: 11.4381
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 56ms/step - accuracy: 0.7274 - loss: 1.2355 - val_accuracy: 0.0796 - val_loss: 11.5103
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7297 - loss: 1.2216 - val_accuracy: 0.0810 - val_loss: 11.5449
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.7329 - loss: 1.2107 - val_accuracy: 0.0787 - val_loss: 11.5713
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.7358 - loss: 1.1971 - val_accuracy: 0.0778 - val_loss: 11.6325
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7379 - loss: 1.1841 - val_accuracy: 0.0789 - val_loss: 11.6928
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7408 - loss: 1.1751 - val_accuracy: 0.0770 - val_loss: 11.7507

In [24]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [25]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word[index] = word

In [36]:
def predictor(model,token,text,maxlen):
  text = text.lower()

  seq = token.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=maxlen, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [39]:
seed_text = "source of happiness is "
next_word = predictor(lstm_model,token,seed_text,maxlen)
print(next_word)

yourself

In [40]:
def generate_text(model,token,seed_text,maxlen,n_words):
  for _ in range(n_words):
    next_word = predictor(model,token,seed_text,maxlen)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [42]:
seed_text="Reason behind success  "
generate_text(lstm_model,token,seed_text,maxlen,10)

'Reason behind success   were never too late it wasnt but im not saying'

In [43]:
import pickle

In [44]:
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(token, f)

In [45]:
with open("max_len.pkl", "wb") as f:
  pickle.dump(maxlen, f)